sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product testn-085
env:
  global:
    -
      # LTD_AWS_ID
      secure: WdgnhRCII2bJSFgJEqxSwQqvsgdVmWN6B9sQbEqyNFBVBrqUzH1t2x4kE3pQanIhueRpbK9+yYVCSnws2Nu7k2EFyS4eQN+WEp/ac/2jbZ32dVIYAM9NVm8soqhzFW/QoVDWrUagufV5hm0KKFUp6jL1PqlrdMlyjhyObXVq+MfSIVuur3Mypd68w7KjNQ7n7F2atzaO8zCUufzcs/6w9rRT8lO8vLeUI/ntEYgwxj68okoFbAyiwJ8NWfSndznhrP6wztIIZtTLaNZPh+9lAL2ltPcy4LryDexTmxSNggUxvkjP/fxPHn48F5wzP6xA5iZi4wCDX2oHFCAs0TedkU7hitnfE3rXFieRRNgXWBvWHul6bT9ko+RN4rzRoErxoeuVQS0nJpCQU7nxCwQwLRkU6MyGQMPyQNyQ/l75zjtT2xpeDItoHjyba+vYuaw2PGcMIG7/qoz3f9HUrabQtiMvJ/AiE7YBFcoSE8gYN7yGcooQVlIJukby1kphk2WubH0Wz0rSEMzn4cF904qAVFI4LLwPMjZafcIky69hpNEqqcrPdXCGTZwHNDlbGCj6m7t+TXv8PAd4mtxVzWZwqlsqlLn4FrniU57Ar1l/syrkBKIgoSu3SMxe/t1VGhgryN8d6OIfXAFIxrT+rkSkq4HEMETInNafJPBqdGedOlk=
    -
      # LTD_AWS_SECRET
      secure: tHykPCUMfOUZZvm/9NWZNPtFj9GESmY72xvvlGMcvrNgsS8aBd2SE16vF04IG8HEOYCTH/Kh1YWixm2o5KsZsE63Iuc8pMVynsZNoKqr/lzvJtj0q3uYYJMfxHyK75NT+0qOXNh11PFpPY3cQ4vBnL/6EUdj8biaT8VLvv5NEYyDcF9IGpX6WlzIDhCs2U0ucAUdHqEXC+Hr9xemX2XAr3SNAkPIYJu0CI9cUBRUN/Px4rUbr+6h78wW44MNo12qQFBH85r8FFk4/5hhCmNLMG4d511Qq2mE6HNjfDl+IzwAVdshJnklXdp2SG1hhswMlrLUeTg9G3mZj/QHlyDm0LCOF/6ddK3ELSgshKfrvPc7kv27uCcw5dwkagC4yrF7/Vfdd8VpNxWM7mBFAryyl9F0feJSm/RjhuLX7EguOOdvBaZPkv5HgWNsnVhfk/ExdtgNYJ8TkWEgcZ2eILDgjeM56Yp1ND8cTKHsaXcxb64H95WMIIIi9EWS6NaEPzXP0FIpQwrEd256GM+jImfxH+ovCBqpGvvwcrRsdpRmt+xzfMfqbFm5ZwExj+jkqkZLKpi+fr+fufgYO4GNcM85sNbkA/QfxIPzazGB/J66dKfU4B7Q2Lg7AD82ncMyoxoKMdSEiuw9JPliVPGRLdsmBL/NlBw8yceYs+fGOIDCxV8=
    -
      # LTD_USERNAME
      secure: jO/TCOnsNDJWjX/mrLdMxEKD2GPbaSEZuGVwuAPe8N/H2B9XpS/X/bZz/xo6BPQ5BXJzpqp6g3e/EIRWHHhkcAKicE++ET1f9xDkHwiqx+TQUN7I7vEUlbgruPxjo3M1fE/I6eABtPeBU3gP88DtNKh4LOo9walQfmjf+zAXUYq2JUCvN/sdUoShvArIctIe5SEPzohaYx8zdPsPeT4Gn6AyEyXlHuczQp2vsB2H+23Ha4kh+hRK+Q+Pga1sjAkddNtP6C3w4D15fPpvwEtrjfDzGK7iDmUd8NkcDA+I3O/Yf/5zRg4dHSzNeeTO9kkCOTnMJvew7uwAbs+g82aIH2E8aV97kwlfSqGkPnXP+eDjsmdXKyN0Y1q1X6RlRrEeEW3a+GFgDQG2Gzra888dam19Pce3GR/ZOjXp8/Q2HxNuj1afCMUMPi2pRycYUrubQjacqXPzXJ9IOpLWbgHhOEdzu+N7T4gck7M4zzlrdlO2bcXQae0mYoZhQmlXtzWGEXIYCvJQnoLek2uawz/deu0fgEv8JJYzlFjBX0ovmBgk0HQ1y93j7twJzJGjGxi250erGph2XIbGGsUFBlT0OiQyvyW3s0oCnLbIiXjI69IyobZOD1BISB9jjG/Vwdw5PmqEgtn+UVQWmBBMA35pakJIpBoaAuHkWTd5ljEZsp4=
    -
      # LTD_PASSWORD
      secure: nPJGoBzzX3rYsr3Ioee7Yfw21yIrXV70/86CvaelfydU7SjZ6HWZA6FvX4vKRMFPlpa7crclo+1m54v8667KdlHpynaJf6gj2M2fDUdkSuy3onuwCoQpVeM+KwB59yvGOiRmPA/wxNOldRCfJrGEM6tQIFdDpjvAe72Ka5vtY05fGxtzkQvrf/yjU2nEYsno4ySAXJl1kBBnfc/6wx0cXOhVl6/OsqgeS3OsUvHS4RpoMOxuBDFWK3PXVhmQlShIfz8TXrUn5J5cqyQ0O+qMa+44fMcxhvvweK/mpB31iyt6RCnzHEgRozFJcobNjINUrQMe4EYzfhVe2HpM+zKZh9J7AI40zaNtzbYkQrmqXBqQEpdj1OvQqdCHIa6Ze3iFNWr0T6zfmCSG0c9bQ+ga3uXWg2yGBooSM92FyyFzQg86xvzqpB+k3q/HR280kgv5M5x7TJ4dYy6YPWOMebroI/hhYk8aNdqrh6dSCn2wVfVYBvUAHq0vv63ggK2Joy+cfOmSnyDsqTLzqGAKgfiiCQffdrYz3yqwv0LmOg40W8a6oKTCxVbHw/2o6F2pRufH9dLgUrfrN6KQ2i235PJNv+X87zYbFbJKG857h7hEpyFKI3UpfA8bn0xP8DOCO9L+bIF+7cgeau9PVwr09v6Fh7XV3Y4tP5rSPzxSI9SMt44=
